Repository vamshi-chidara/expertiza, pull requests merged in 2022-03, with the labels that each got.

#1 Refactor create and update methods in response controller
  app/controllers/response_controller.rb
Labels: enhancement

#2 Refactoring changes for create_answers, update and save method in response controller
  app/controllers/response_controller.rb
  app/models/awarded_badge.rb
Labels: enhancement

#6 Update to the response_spec.rb test case file to reflect method name changes.
  spec/models/response_spec.rb
Labels: bug

#8 Changes to authorization method which is used to display calibration results for a reviewer.
  app/controllers/response_controller.rb
Labels: bug

#9 comments for delete and action_allowed methods in response_controller
  app/controllers/response_controller.rb
Labels: documentation

#12 Changes to fix rubocop errors
  app/controllers/response_controller.rb
  app/helpers/response_helper.rb
  app/models/assignment_questionnaire.rb
  app/models/awarded_badge.rb
Labels: bug
